### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-midknight_appdev#28]
Your architecture is that every route is a whole set of component each has the app-header. This is why your component template is cluttered like this one:
https://github.com/PUP-BSIT/project-midknight_appdev/blob/294d59568fef43a1d760a6017f7dca03f9675a47/kajas/src/app/add-artwork/add-artwork.component.html#L1-L87

This is not very pleasing and not a good practice. Instead, put your header in the root component like this:
![image](https://github.com/PUP-BSIT/project-midknight_appdev/assets/76401444/2f9c64a5-ed40-4909-b5e2-f3b8c1435d38)

Then you can hide/show your header using the [router event](https://medium.com/@deepachaurasia33/how-to-show-or-hide-component-on-basis-of-route-in-angular-a5c691b099fa).

Also, remove unnecessary DIV tags. There were lots of div that are so unnecessary making your HTML template file like a callback hell. The reason we use Angular is to make each component modular. I gave you a reference on how to use [MatDialog](https://material.angular.io/components/dialog/overview) to make it easy for you and follow the best practice but you choose to implement your own dialog that you cannot re-use. What you did here forfeits the purpose of Angular. I also expected that you make research and do things the Angular way, not the trying hard VanillaJS way.

I know it's in the late stage of the development but I'm hoping you can refactor your codes. If there's no sufficient time, just note this on your future project in case you want to pursue this technology. Remember that Angular is made to make your code beautiful and maintainable.

**Comment by Valerio-SirLance** [comment]
Thank you sir for the detailed feedback! I will discuss these points with the team, and we'll do our best to address them while completing our current development stage. We'll try our best to refactor the code after we finish the requirements to improve the architecture and maintainability as suggested. These insights will be valuable for us especially in the future. 

Let me close this issue with this comment, and again, thank you sir!!!
